# Zoo Data Set prediction

## This is a classificcation problem. Here I am using various classification Machine Learning algorithms

### Importing the necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Now reading the dataset using Pandas libraries

In [2]:
df=pd.read_csv(r'D:\Kaggle\zoo.csv')

#### Doing some EDA 

In [3]:
df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [4]:
df.shape

(101, 18)

In [5]:
df.isnull().sum()

animal_name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
class_type     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
 17  class_type   101 non-null    int64 
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [7]:
df['class_type'].nunique()

7

In [8]:
df.drop('animal_name',axis=1,inplace=True)

In [9]:
x=df.drop('class_type',axis=1)

In [10]:
y=df['class_type']

In [11]:
y.shape

(101,)

In [12]:
x.shape

(101, 16)

#### Splitting the data set to train and test datasets.

In [13]:
from sklearn.model_selection import train_test_split


In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.23,random_state=0)

## Logistic Regression 

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model_LR=LogisticRegression()

In [17]:
model_LR.fit(x_train,y_train)

C:\Users\sreer\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
model_LR.score(x_test,y_test)

1.0

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
y_pred_LR=model_LR.predict(x_test)

In [21]:
confusion_matrix(y_test,y_pred_LR)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

## Decision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
model_DT=DecisionTreeClassifier()

In [24]:
model_DT.fit(x_train,y_train)

DecisionTreeClassifier()

In [25]:
model_DT.score(x_test,y_test)

1.0

In [26]:
y_pred_DT=model_DT.predict(x_test)

In [27]:
confusion_matrix(y_test,y_pred_DT)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
model_RF=RandomForestClassifier()

In [30]:
model_RF.fit(x_train,y_train)

RandomForestClassifier()

In [31]:
model_RF.score(x_test,y_test)

1.0

In [32]:
y_pred_RF=model_RF.predict(x_test)

In [33]:
confusion_matrix(y_test,y_pred_RF)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

## Support Vector Machine 

In [34]:
from sklearn.svm import SVC

In [35]:
model_svc=SVC()

In [36]:
model_svc.fit(x_train,y_train)

SVC()

In [37]:
model_svc.score(x_test,y_test)

0.9583333333333334

In [38]:
y_pred_svc=model_svc.predict(x_test)

In [39]:
confusion_matrix(y_test,y_pred_svc)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

#### Though the model gives an aacuracy of 96%, since the dataset is small, I am trying to use a different kernel for better accuracy.

In [40]:
#### Now building the model with a linear Kernel, earlier it was 'radial basis function'

In [41]:
model_svcl=SVC(kernel='linear')

In [42]:
model_svcl.fit(x_train,y_train)

SVC(kernel='linear')

In [43]:
model_svcl.score(x_test,y_test)

1.0

In [44]:
y_pred_svcl=model_svcl.predict(x_test)

In [45]:
confusion_matrix(y_test,y_pred_svcl)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

## Ada Boost Classifier

In [46]:
from sklearn.ensemble import AdaBoostClassifier

In [47]:
model_ada = AdaBoostClassifier()

In [48]:
model_ada.fit(x_train,y_train)

AdaBoostClassifier()

In [49]:
model_ada.score(x_test,y_test)

0.75

In [50]:
y_pred_Ada = model_ada.predict(x_test)

In [51]:
confusion_matrix(y_test,y_pred_Ada)

array([[8, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0]], dtype=int64)